In [27]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np
from tensorflow.keras.preprocessing import image

In [34]:
def load_dataset():
    train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)
    test_datagen = ImageDataGenerator(rescale = 1./255)
    training_set = train_datagen.flow_from_directory('train',
                                                 target_size = (32, 32),
                                                 batch_size = 32,
                                                 class_mode = 'categorical')
    test_set = test_datagen.flow_from_directory('test',
                                            target_size = (32, 32),
                                            batch_size = 32,
                                            class_mode = 'categorical')
    return training_set, test_set

In [35]:
def define_model():
    classifier = Sequential()
    classifier.add(Conv2D(32, (3, 3), input_shape = (32, 32, 3), activation = 'relu'))
    classifier.add(MaxPooling2D(pool_size = (2, 2)))
    classifier.add(Flatten())
    classifier.add(Dense(units = 128, activation = 'relu'))
    classifier.add(Dense(units = 10, activation = 'softmax'))
    classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
    return classifier

In [38]:
def evaluate_model():
    dataX, dataY = load_dataset()
    model = define_model()
    model.fit_generator(dataX,
                         steps_per_epoch = 20000,
                         epochs = 2,
                         validation_data = dataY,
                         validation_steps = 3000
                       )
    model.save('digitRecog.h5')

In [39]:
evaluate_model()

Found 20000 images belonging to 10 classes.
Found 3000 images belonging to 10 classes.
Epoch 1/2
625/625 [==============================] - 61s 98ms/step - loss: 0.3598 - accuracy: 0.8787 - val_loss: 0.1193 - val_accuracy: 0.9587
Epoch 2/2
625/625 [==============================] - 60s 96ms/step - loss: 0.1357 - accuracy: 0.9570 - val_loss: 0.0814 - val_accuracy: 0.9713


In [40]:
from tensorflow.keras.models import load_model

In [52]:
def predict_digit(image_path):
    model = load_model("digitRecog.h5")
    individual_image=image.load_img(image_path, target_size = (32, 32))
    individual_image = image.img_to_array(individual_image)
    individual_image = np.expand_dims(individual_image, axis = 0)
    result = model.predict(individual_image)
    return result[0]

In [50]:
predict_digit('image.jpg')

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [53]:
predict_digit('first.png')

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [54]:
predict_digit('second.png')

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32)

In [43]:
training_set.class_indices

{'digit_0': 0,
 'digit_1': 1,
 'digit_2': 2,
 'digit_3': 3,
 'digit_4': 4,
 'digit_5': 5,
 'digit_6': 6,
 'digit_7': 7,
 'digit_8': 8,
 'digit_9': 9}